name: Deploy landing to geooooo.github.io

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout landing repo
        uses: actions/checkout@v4

      - name: Deploy to geooooo.github.io
        uses: peaceiris/actions-gh-pages@v4
        with:
          personal_token: ${{ secrets.GH_PAGES_TOKEN }}
          external_repository: geooooo/geooooo
          publish_branch: public
          publish_dir: ./
          force_orphan: true
          cname: yury-kornienko.pro
